all:
  hosts:
    web1:
      ansible_host: 192.168.1.153  # <--- IMPORTANTE: Cambia esto por TU IP REAL
      ansible_user: deploy         # El usuario que creaste en el paso 1 [cite: 14]
      ansible_python_interpreter: /usr/bin/python3